# Generated by Django 3.1.4 on 2021-01-07 02:02

from django.db import migrations, models
import produto.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('picture', stdimage.models.StdImageField(upload_to=produto.models.get_file_path, verbose_name='Imagem')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('information', models.TextField(max_length=700, verbose_name='Caractristicas')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
